### ISSUE TITLE
Unicode support for presets

### ISSUE THREAD

**Issue by jbruechert** [xHain-hackspace/tr33#1]
It seems like presets containing special unicode characters in their name can not be saved or at least not loaded again.

**Comment by Reimerei** [comment]
Thanks for the report.
Any utf-8 character should be supported. I just had a look and it seems to work. There is a minimum of 2 characters though.

**Comment by jbruechert** [comment]
Nice to hear that it works. I'll try to find the problem with the specific name I tried when I'm at the xHain next time :)
